### PR TITLE
Simple support for Map[String,String]

### PR DESCRIPTION
**Pull request by lustefaniak**

### CODE REVIEW

**Comment by zhongl** [comment]
IMO, Map is just another style of object, which is not necessary.

**Comment by lustefaniak** [comment]
Hi,
In my usecase I don't know what will be keys of  the map(I know only defaults) - I'm passing all the key value pairs to external library so I'm not really able to achieve same functionality without map support. Of course I can just use that code manually, and retrieve key from `config`, but I think this way it is simpler as path is auto generated.

**Comment by zhongl** [comment]
Em... it sounds reasonable.

Thank you again.

**Comment by lustefaniak** [comment]
Thanks, and many thanks for great library ;)

**Pull request merged**
